core/urls.py
from .views import setup, activate, update_quote, check_user
from django.conf.urls import patterns, url


urlpatterns = patterns('', 
	url(r'^setup/$', setup, name='user-settings'),
	url(r'^activate/$', activate, name='activate'),
	url(r'^update_quote/$', update_quote, name='update_quote'),
	url(r'^check/$', check_user, name='check_user'),

)

projects/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('', 
	url(r'^list/$', ProjectListView.as_view(), name='my_projects'),
	url(r'^supervision-list/$', StaffProjectListView.as_view(), name='supervision'),
	url(r'^details/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', ProjectDetailView.as_view(), name='project_detail'),
	url(r'^edit-project/(?P<project_id>\d+)/$', update_project, name='edit-project'),
	url(r'^add/$', new_project, name='new_project'),
)

result_analytics/urls.py
"""result_analytics URL Configuration
"""

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 
from result_analytics.views import index, home, register_user, register_success
from django.views.static import serve
from .views import home, change_password, activation_sent, activate

urlpatterns = [ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^assignments/', include('assignments.urls', namespace='assignment')),
    url(r'^$', index, name='user_index'),
    url(r'^prompt$', TemplateView.as_view(template_name='_signup_prompt.html'), name='signup-prompt'),
    url(r'^dashboard/$', home, name='dashboard'),
    url(r'^results/', include('results.urls', namespace='results')),
    url(r'^analytics/', include('analyzer.urls', namespace='analyzer')),
    url(r'^staff/', include('staff.urls')),
    url(r'^setup/', include('core.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^notification/', include('notifications.urls', namespace='notifications')),
    url(r'^institution/', include('institutions.urls', namespace='institution')),
    url(r'^collaborate/', include('collaborations.urls', namespace="collaborate")),
    url(r'^forum/', include('forum.urls')),
]
urlpatterns+=patterns('django.contrib.auth.views',
        url(r'^login/$', 'login', {'template_name': 'login.html'}, name='result_login'),
        url(r'^password-reset/$', 'password_reset', {
            'template_name': 'password_reset.html',
            'email_template_name': 'password_reset_email.html',
            'subject_template_name':'password_reset_subject.txt',
            'post_reset_redirect': ('result_reset_done'),
            'html_email_template_name':'password_reset_email.html',
            }, name="result_password_reset"),
        url(r'^password-reset-done/$', 'password_reset_done', {'template_name':'password_reset_done.html',}, name="result_reset_done"),
        url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'password_reset_confirm',{'template_name':'password_reset_confirm.html',}, name="photobox_reset_confirm"),
        url(r'^password-reset-complete/$', 'password_reset_complete',{'template_name':'password_reset_complete.html',}, name="result_reset_complete"), 
        url(r'^logout/$', 'logout', {'next_page': 'result_login'}, name="result_logout"),
)

urlpatterns+=patterns('',
        url(r'^successful/$', register_success, name="result_success"),
        url(r'^signup/$', register_user, name="result_signup"),
        url(r'^start/signup/$', TemplateView.as_view(template_name='signup.html'), name="start-signup"),
        url(r'^change-password/$', change_password, name="change-password"),
        url(r'^howitworks$', TemplateView.as_view(template_name= 'how.html'), name='how-it-works'),
        url(r'^who-we-are/$', TemplateView.as_view(template_name='about.html'), name='about'),
        url(r'^pricing$', TemplateView.as_view(template_name='pricing.html'), name='pricing'),
        url(r'^account_activation_sent/$', activation_sent, name='account_activation_sent'),
        url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

results/urls.py
from django.conf.urls import patterns, url
from .views import (
                add_result, result_list,
                upload_csv, grading_setting, result_by_student, 
                import_data, export_excel, full_detail, 
                overall_result, StaffBasedResultView, edit_result
                )

urlpatterns = patterns('',
    url(r'^add_results/$', add_result, name='add_result'),
    url(r'^edit-result/$', edit_result, name='edit_result'),
    url(r'^grading-scheme$', grading_setting, name='grading-setting'),
    url(r'^upload_csv/$', upload_csv, name='upload_csv'),
    url(r'^lecturer-results/$', StaffBasedResultView.as_view(), name='staff_result'),
    url(r'^import_results/$', import_data, name='result_import'),
    url(r'^students_import/$', import_data, name='student_import'),
    url(r'^$', result_list, name='students_results'),
    url(r'^own_results/(?P<student_slug>[\w-]+)/$', result_by_student, name='personal_results'),
    url(r'^overall_results/(?P<student_slug>[\w-]+)/$', overall_result, name='all_results'),
    url(r'^(?P<student_slug>[\w-]+)/result_details/$', full_detail, name='full_detail'),
    url(r'^excel/$', export_excel, name='export_excel'),
)

students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .forms import *
from .views import (StudentListView, student_profile, request_help,
                    export_excel, create_student, update_photo, student_chart_json,
                    mapper_excel_generator, generate, generate_mapper_json,
                    edit_profile, StudentAnalyticsView, import_student_data, upload_student_csv)
urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^analysis/$', login_required(StudentAnalyticsView.as_view()), name='student_analytics'),
    url(r'^new_student/$', create_student, name='create_student'),
    url(r'^profile/(?P<student_slug>[\w-]+)/$', student_profile , name='student_account'),
    url(r'^excel/$', export_excel, name='export_excel'),
    url(r'^mapper/$', mapper_excel_generator, name='mapper'),
    url(r'^update-profile/$', edit_profile, name='edit-profile'),
    url(r'^mapper/generator/$', generate, name='generate'),
    url(r'^update-photo/$', update_photo, name='update_photo'),
    url(r'^student-json/$', student_chart_json, name='student_chart_json'),
    url(r'^mapper-json/$', generate_mapper_json, name='mapper-json'),
    url(r'^ineed/assistance/(?P<student_id>\d+)/$', request_help , name='help'),
    url(r'^bulk-upload/$', import_student_data , name='student-import'),
    url(r'^upload/$', upload_student_csv , name='student-upload'),

)

projects/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
import uuid
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from staff.models import Lecturer


class Project(models.Model):
    '''Personal and school projects that a student can participate in'''

    student = models.ForeignKey('students.Student', null=True)
    name = models.CharField(max_length=250, null=True)
    description = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=50, null=True)
    file = models.FileField(upload_to='students/projects/%Y/%m/%d/', blank=True)
    supervisor = models.ForeignKey(Lecturer, null=True, blank=True) 
    tag = models.CharField(max_length=150, blank=True, null=True)
    slug = models.SlugField(blank=True, unique=True)
    date_created = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _(u'Student Project')
        verbose_name_plural = _(u'Student Projects')
        ordering = ('name',)

    def __str__(self):
        return self.name

    def save(self, **kwargs):
    	orig = slugify(self.name)
    	self.slug = "%s-%s" % (orig, uuid.uuid4())
    	super(Project, self).save(**kwargs)

    #@models.permalink
    def get_absolute_url(self):
    	return reverse('project_detail', args=[self.pk, self.slug])


# class ProjectSupervision(models.Model):
# 	ACTIVE, DECLINED, COMPLETED, REVOKED = ('A', 'D', 'C', 'R')
# 	PROJECT_STATUS = (
# 		(ACTIVE, 'Active'),
# 		(DECLINED, 'Declined'),
# 		(COMPLETED, 'Completed'),
# 		(REVOKED, 'Revoked')
# 	)
# 	lecturer = models.ForeignKey(Lecturer, null=True)
# 	project = models.ForeignKey(Project, null=True)
# 	status = models.CharField(max_length=1, choices=PROJECT_STATUS, default='A')
# 	last_checked = models.DateTimeField(auto_now=True, null=True)

# 	def __str__(self):
# 		return "%s-->%s" % (lecturer, self.project)

students/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from institutions.models import *
import uuid
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models import signals
from django.utils.timezone import now
from river.models.fields.state import StateField


(SINGLE, MARRIED, WIDOWED, DIVORCED) = range(1, 5)
MARITAL_STATUS_CHOICES = (
    (SINGLE, _(u'Single')),
    (MARRIED, _(u'Married')),
    (WIDOWED, _(u'Widowed')),
    (DIVORCED, _(u'Divorced')),
)

SEX_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

(REGULAR, SANDWICH, CEP, DIPLOMA, OTHERS) = range(1,6)
PROGRAM_CHOICES = (
    (REGULAR, _(u'Regular')),
    (SANDWICH, (u'Sandwich')),
    (CEP, (u'CEP')),
    (DIPLOMA, (u'Diploma')),
    (OTHERS, (u'Others')),
)

RELIGION_CHOICES = (
    (1, 'Christianity'),
    (2, 'Islam'),
    (3, 'Others'),
)

BLOOD_GROUP_CHOICES = (
    ('A', 'A'),
    ('AB', 'AB'),
    ('B', 'B'),
    ('O+', 'O+'),
    ('O-', 'O-'),
)

GENOTYPE_CHOICES = (
    ('AA', 'AA'),
    ('AS', 'AS'),
    ('SS', 'SS'),
)


class StudentManager(models.Manager):
    def get_active_students(self):
        """Returns all employees, still in employment (excluding ex-employees)."""
        return super(StudentManager, self).get_query_set().exclude(status='E')


class Bank(models.Model):
    name = models.CharField(max_length=150, unique=True)


    class Meta:
        verbose_name = _(u'Bank')
        verbose_name_plural = _(u'Banks')
        ordering = ('name',)

    def __str__(self):
        return self.name


class PhoneCategory(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        verbose_name = _(u'Phone Category')
        verbose_name_plural = _(u'Phone Categories')
        ordering = ('name',)

    def __str__(self):
        return self.name




class Student(models.Model):
    STATUS_CHOICES = (
        ('A', _(u'Active')),
        ('G', _(u'Graduated')),
        ('S', _(u'Suspended')),
        ('E', _(u'Expelled')),
    )

    user = models.OneToOneField(User, related_name='student', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='uploads', blank=True)
    email = models.EmailField(blank=True)
    last_name = models.CharField(verbose_name=_(u'Surname'), max_length=50, null=True)
    first_name = models.CharField(verbose_name=_(u'First name'), max_length=50, null=True)
    middle_name = models.CharField(verbose_name=_(u'Middle name'), max_length=50, blank=True)
    user_status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='A', blank=True, null=True)
    reg_number = models.CharField(max_length=30)
    faculty= models.ForeignKey(Faculty, null=True)
    department = models.ForeignKey(Department, null=True)
    bank = models.ForeignKey(Bank, blank=True, null=True)
    bank_account_number = models.CharField(max_length=20, blank=True, null=True)
    marital_status = models.PositiveSmallIntegerField(choices=MARITAL_STATUS_CHOICES, blank=True, null=True)
    sex = models.CharField(max_length=1, null=True, choices=SEX_CHOICES)
    level = models.PositiveIntegerField(choices=settings.LEVEL_CHOICES, blank=True)
    institution = models.ForeignKey(Institution, null=True)
    program_type = models.PositiveIntegerField(choices=PROGRAM_CHOICES, null=True, blank=True)
    birth_date = models.DateField(blank=True, null=True, db_index=True)
    library_id_number = models.PositiveIntegerField(blank=True, null=True)
    school_id_number = models.PositiveIntegerField(blank=True, null=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    date_gained_admission = models.DateField(auto_now=True)
    blood_group = models.CharField(max_length=2, choices=BLOOD_GROUP_CHOICES, blank=True)
    genotype = models.CharField(max_length=2, choices=GENOTYPE_CHOICES, blank=True)
    national_id_number = models.CharField(verbose_name=_(u"National ID Number"), max_length=50, blank=True)
    year_of_admission = models.DateField()
    course_duration = models.PositiveIntegerField()
    religion = models.PositiveIntegerField(choices=RELIGION_CHOICES, blank=True, null=True)
    permanent_address = models.TextField(blank=True)
    state_of_residence = models.ForeignKey('states.State', null=True,blank=True, related_name='students_residence')
    country = models.ForeignKey('states.Country', related_name='country_of_residence', null=True, blank=True)
    state_of_origin = models.ForeignKey('states.State', related_name='students_origin', blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    #clearance_status = StateField(editable=False, default=None)
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    objects = StudentManager()


    class Meta:
        verbose_name = _(u'Student')
        verbose_name_plural = _(u'Students')
        ordering = ('last_name',)



    def __str__(self):
        names = [self.last_name]
        if self.middle_name:
            names.append(self.middle_name)
        names.append(self.first_name)
        return u' '.join(names)


    @property
    def full_name(self):
        """Returns this employee's full name."""
        names = [self.last_name]
        if self.middle_name:
            names.append(self.middle_name)
        names.append(self.first_name)
        return u' '.join(names)

    @property
    def get_program_type(self):
        program_type = {1: 'Regular', 2: 'Sandwich', 3: 'CEP', 4: 'Diploma', 5: 'Others'}
        if self.program_type:
            return program_type[self.program_type]

    @property
    def get_marital_status(self):
        marital_status = {1: 'Single', 2: 'Married', 3: 'Widowed', 4: 'Divorces'}
        if self.marital_status:
            return marital_status[self.marital_status]

    @property
    def year_of_graduation(self):
        if self.year_of_admission:
            return (self.year_of_admission.year + self.course_duration)

    def get_absolute_url(self):
        return reverse('students:student_account', kwargs={'student_slug':self.slug})


class Document(models.Model):
    """Represents electronic documents that form part of a student's record."""

    student = models.ForeignKey(Student)
    attached_file = models.FileField(upload_to='uploads/docs/%Y/%m/%d/')
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(_(u'Description'), blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _(u'Attached Document')
        verbose_name_plural = _(u'Attached Documents')

    def __str__(self):
        return self.name

    def delete(self, **kwargs):
        self.file.delete()
        return super(Document, self).delete(**kwargs)

    def current_level(self):
        level = (self.level+100)
        return level

class Scholarship(models.Model):
    '''Scholarship schemes a student is involved in or wishes to be involved in'''
    student = models.ForeignKey(Student, null=True, blank=True)
    title = models.CharField(max_length=250, blank=True, null=True)
    provider = models.CharField(max_length=250, blank=True, null=True)
    location = models.CharField(max_length=150, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _(u'Scholarship')
        verbose_name_plural = _(u'Scholarships')
        ordering = ('title',)

    def __str__(self):
        return "%s" %(self.title)


class UniqueMapper(models.Model):
    reg_number = models.CharField(max_length=30)
    short_institution_name = models.CharField(max_length=5, null=True)
    unique_map = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _(u'Unique Mapper')
        verbose_name_plural = _(u'Unique Mappers')
        ordering = ('short_institution_name',)

    def __str__(self):
        return "%s-%s" % (self.short_institution_name.upper(), self.unique_map)


    def save(self, **kwargs):
        uuid_found = True
        while uuid_found:
            get_uuid = uuid.uuid4()
            self.unique_map = "%s-%s" % (self.short_institution_name, get_uuid)
            if not UniqueMapper.objects.filter(unique_map=self.unique_map).exists():
                uuid_found = False
        super(UniqueMapper, self).save(**kwargs)

students/templates/students/_document.html
<div class="search-result">
    {% if document %}
    {% if is_onw_profile %}<a class="delete-section pull-right" href="#">Delete</a>{% endif %}
    {% endif %}
    <p>
        <i class="icons icons-sm icons-file"></i>
        {% if id_own_profile %}
        <a href="{{ document.attached_file.url }}" target="_blank">{{ document.name|title }}</a>
        {% else %}
        {{ document.name|title }}
        {% endif %}
    </p>
    {% if document.description %}
    <div>
        {{ document.description }}
    </div>
    {% endif %}
</div>

students/templates/students/_personalinformation.html
<table class="table">
    <tbody>
        {% if student.sex %}
        <tr>
            <th scope="row" style="width:35%">Sex</th>
            <td>{{ student.get_sex_display }}</td>
        </tr>
        {% endif %}
        {% if student.blood_group %}
        <tr>
            <th scope="row">Blood group</th>
            <td>{{ student.blood_group }}</td>
        </tr>
        {% endif %}
        {% if student.genotype %}
        <tr>
            <th scope="row">Genotype</th>
            <td>{{ student.genotype }}</td>
        </tr>
        {% endif %}
        {% if student.marital_status %}
        <tr>
            <th scope="row">Marital status</th>
            <td>{{ student.get_marital_status_display }}</td>
        </tr>
        {% endif %}
        {% if student.address %}
        <tr>
            <th scope="row">Address</th>
            <td>{{ student.address|linebreaks }}</td>
        </tr>
        {% endif %}
        {% if student.permanent_address %}
        <tr>
            <th scope="row">Permanent address</th>
            <td>{{ student.permanent_address|linebreaks }}</td>
        </tr>
        {% endif %}
        {% if student.state_of_residence %}
        <tr>
            <th scope="row">State of residence</th>
            <td>{{ student.state_of_residence }}</td>
        </tr>
        {% endif %}
        {% if student.state_of_origin %}
        <tr>
            <th scope="row">State of origin</th>
            <td>{{ student.state_of_origin }}</td>
        </tr>
        {% endif %}
        {% if student.lga %}
        <tr>
            <th scope="row">LGA</th>
            <td>{{ student.lga }}</td>
        </tr>
        {% endif %}
        {% if student.country %}
        <tr>
            <th scope="row">Country</th>
            <td>{{ student.country }}</td>
        </tr>
        {% endif %}
        {% if student.passport_number %}
        <tr>
            <th scope="row">Passport number</th>
            <td>{{ student.passport_number }}</td>
        </tr>
        {% endif %}
        {% if student.national_id_number %}
        <tr>
            <th scope="row">National ID number</th>
            <td>{{ student.national_id_number }}</td>
        </tr>
        {% endif %}
        {% if student.religion %}
        <tr>
            <th scope="row">Religion</th>
            <td>{{ student.get_religion_display }}</td>
        </tr>
        {% endif %}
        {% if student.maiden_name %}
        <tr>
            <th scope="row">Maiden name</th>
            <td>{{ student.maiden_name }}</td>
        </tr>
        {% endif %}
        {% if student.mothers_maiden_name %}
        <tr>
            <th scope="row">Mother's maiden name</th>
            <td>{{ student.mothers_maiden_name }}</td>
        </tr>
        {% endif %}
    </tbody>
</table>

students/templates/students/_project.html
<div class="search-result">
    {% if project %}
    {% if is_own_profile %}<a class="delete-section pull-right" href="#">Delete</a>{% endif %}
    {% endif %}
    <p>
        <i class="icons icons-sm icons-book"></i>
        {% if is_own_profile %}
        <a href="{{ project.file.url }}" target="_blank">{{ project.name|title }}</a>
        {% else %}
        {{ project.name|title }}
        {% endif %}
    </p>
    {% if project.description %}
    <div>
        {{ project.description }}
    </div>
    {% endif %}
</div>

students/templates/students/accounts.html
{% extends 'dashboard.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block breadcrumbs %}<a>User Account</a>{% endblock %}

{% block content %}
<div style="margin-bottom: 30px;">
   <h3 style="border-bottom: 2px solid rgba(0,0,0,0.04);">User Account <span style="float: right; font-size: 16px;"><a href="{% url 'students:edit-profile' %}" class="pull-right"><i class="icons icons-sm icons-edit"> Edit</i></a></span></h3>
</div>
{% include 'students/_account_details.html' %}
{% endblock %}

{% block side%}
<div class="panel panel-default" style="min-height: 300px; margin-top: 5px;">
	<div class="panel-body">
		<div class="sub-panel add-padding">
			{% if student.photo %}
			{% thumbnail student.photo "100x100" crop="center" as im %}
			<img  class="img-circle" src="{{im.url}}" width="{{im.width}}" height="{{im.height}}">
			{% endthumbnail %}
			{% else %}
			<i class="icons icons-x-lg icons-user" style="font-size: 6em;"></i>
			{% endif %}
			<a href="{{student.get_absolute_url}}"><h3><strong>{{student}}</strong></h3></a>
			<p>{{student.department}}, Faculty of {{student.faculty}}</p>
			<form method="POST" id="form_update" action="{% url 'students:update_photo' %}" enctype="multipart/form-data">{% csrf_token %}
				<input id="id_photo" type="file" style="position: absolute; top: -100px;" name="photo">
				<input type="hidden" name="user_id" value="{{student.id}}">
				<input type="submit" id="frm_submit" hidden="hidden">
				<button id="photo_change" class="btn btn-sm custom-btn" type="button">Change Photo</button>
			</form>
			<div id="container" style="display: none;">
				<h5>Image Preview</h5>
				<img id="img_preview" src="" style="width: 100px; height: 110px; border-radius: 4px; padding: 3px; border: 2px solid #f1f1f1;">
			</div>
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-body">
		<div class="sub-panel">
			{% if student.institution.logo %}
			{% thumbnail student.institution.logo "100x110" crop="center" as im %}
			<img src="{{ im.url}}" width="{{im.width}}" height="{{im.height}}">
			{% endthumbnail %}
			{% else %}
			<img src="{% static 'images/grade-sm-2.png' %}" width="100" height="100">
			{% endif %}
		</div>
		{% if student.institution %}
		<div>
			{{student.institution}}
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/cbpFWTabs.js' %}"></script>
<script>
	new CBPFWTabs( document.getElementById( 'tabs' ) );
</script>

<script>
	file_input = document.getElementById('id_photo');
	$("button").click(function() {
		console.log(this);
		file_input.click(); 

	});

	function preview_image(file_input_id, preview_image_id){
        var ofReader = new FileReader();
        ofReader.readAsDataURL(document.getElementById(file_input_id).files[0]);
        ofReader.onload = function(ofReader){
            document.getElementById(preview_image_id).src = ofReader.target.result;
        }
    }

    $('#id_photo').change(function(){
        preview_image('id_photo','img_preview');
        $('#container').css('display', 'inline-block');
        $('#frm_submit').click();
    	});   
</script>
{% endblock %}

students/templates/students/generate_mapper.html
{% extends "dashboard.html" %} 
{% load staticfiles %} 

{% block breadcrumbs %} Import Result &raquo; {% endblock %} 

{% block content %}
<div style="margin-bottom: 30px;">
    <h3 class="page-header">Student Reg-Map Generator</h3>
</div>
<div class="col-md-10 center-block">
    <p>A <strong>Reg-Map</strong> is a unique ID that maps a students registration number to a particular school. 
    It enables and saves the school the huddle of creating a user account for each student.
     </p>
     <br>
     <h4 class="head-color"><strong>STEPS</strong></h4>
     <p>1) Save all students reg numbers in an excel file with two columns: <br> (i)Reg Number and (ii) Short Code of Institution</p>
     <p>2) Upload it to the Reg-Mapper and it generates unique IDs for each students and returns thesame file as a downloadable  having the last column containing the Mapped ID</p>
     <p>3) This can be pasted on a notice board for students to copy and used for their sign up</p>
</div>
<div class="col-md-10 center-block panel panel-default" style="margin-bottom: 30px; padding: 15px; background: #f9f9f9;">
    <form method="POST" action="{% url 'students:generate' %}" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group">
            {{ form }}
            <div style="margin-top: 30px; width: 40%;">
                <button id="import" disabled="disabled" class="btn custom-btn btn-sm btn-block" type="submit">Generate Mapper</button> </div>
        </div>
        <div class="form-group">
            <p class="text-muted">An excel file will be downloaded once you click the "Generate Mapper" button.
             Check your local downloads folder for the file</p>
        </div>
    </form>
</div>
<div class="col-md-12 scroll" style="padding: 4px; width: 100%; overflow-x: auto; border-radius: 3px; border: 1px solid #f1f1f1;">
    <div id="import_container">
    </div>
</div>
{% endblock %} 

{% block extrajs %}
<script>
    $('#id_file').change(function() {
        $('#import').attr('disabled', false);
    });
</script>
{% endblock %}

students/templates/students/student_import.html
{% extends "dashboard.html" %}
{% load staticfiles %}

{% block breadcrumbs %} Import Result &raquo; {% endblock %}

{% block content %}
<div style="margin-bottom: 30px;">
    <h3 class="page-header">Students Upload</h3>
</div>
<div class="col-md-8 center-block panel panel-default" style="margin-bottom: 30px; padding: 15px; background: #f9f9f9;">
    <form method="POST" action="{% url 'students:student-upload' %}" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group">
            {{ form }}
            <div style="margin-top: 30px; width: 40%;">
                <button id="import" disabled="disabled" class="btn custom-btn btn-sm btn-block" type="submit">Upload</button> </div>
        </div>
    </form>
</div>
<div class="col-md-8 center-block">
  <p style="text-align: center;">You can download a template format for the file <a href="{% static 'samples/students_upload.csv' %}" style="color: #43a3ba; border-bottom: 1px solid; padding-bottom: 3px;">HERE</a></p>
</div>
{% endblock %}

{% block extrajs %}
<script>
    $('#id_file').change(function() {
        $('#import').attr('disabled', false);
    });
</script>
{% endblock %}