core/urls.py
from .views import setup, activate, update_quote, check_user
from django.conf.urls import patterns, url


urlpatterns = patterns('', 
	url(r'^setup/$', setup, name='user-settings'),
	url(r'^activate/$', activate, name='activate'),
	url(r'^update_quote/$', update_quote, name='update_quote'),
	url(r'^check/$', check_user, name='check_user'),

)

courses/urls.py
from django.conf.urls import patterns, url
from .views import new_course, reg_course, CourseListView, edit_course, RegisteredCourseView

urlpatterns = patterns('',
    url(r'^create_course/$', new_course, name='create_course'),
    url(r'^edit/(?P<course_id>\d+)/$', edit_course, name='edit'),
    url(r'^reg/$', reg_course, name='reg_course'),
    url(r'^registered/$', RegisteredCourseView.as_view(), name='course-registered'),
    url(r'^list$', CourseListView.as_view(), name='course-list')
)

result_analytics/urls.py
"""result_analytics URL Configuration
"""

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 
from result_analytics.views import index, home, register_user, register_success
from django.views.static import serve
from .views import home, change_password, activation_sent, activate

urlpatterns = [ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^assignments/', include('assignments.urls', namespace='assignment')),
    url(r'^$', index, name='user_index'),
    url(r'^prompt$', TemplateView.as_view(template_name='_signup_prompt.html'), name='signup-prompt'),
    url(r'^dashboard/$', home, name='dashboard'),
    url(r'^results/', include('results.urls', namespace='results')),
    url(r'^analytics/', include('analyzer.urls', namespace='analyzer')),
    url(r'^staff/', include('staff.urls')),
    url(r'^setup/', include('core.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^notification/', include('notifications.urls', namespace='notifications')),
    url(r'^institution/', include('institutions.urls', namespace='institution')),
    url(r'^collaborate/', include('collaborations.urls', namespace="collaborate")),
    url(r'^forum/', include('forum.urls')),
]
urlpatterns+=patterns('django.contrib.auth.views',
        url(r'^login/$', 'login', {'template_name': 'login.html'}, name='result_login'),
        url(r'^password-reset/$', 'password_reset', {
            'template_name': 'password_reset.html',
            'email_template_name': 'password_reset_email.html',
            'subject_template_name':'password_reset_subject.txt',
            'post_reset_redirect': ('result_reset_done'),
            'html_email_template_name':'password_reset_email.html',
            }, name="result_password_reset"),
        url(r'^password-reset-done/$', 'password_reset_done', {'template_name':'password_reset_done.html',}, name="result_reset_done"),
        url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'password_reset_confirm',{'template_name':'password_reset_confirm.html',}, name="photobox_reset_confirm"),
        url(r'^password-reset-complete/$', 'password_reset_complete',{'template_name':'password_reset_complete.html',}, name="result_reset_complete"), 
        url(r'^logout/$', 'logout', {'next_page': 'result_login'}, name="result_logout"),
)

urlpatterns+=patterns('',
        url(r'^successful/$', register_success, name="result_success"),
        url(r'^signup/$', register_user, name="result_signup"),
        url(r'^start/signup/$', TemplateView.as_view(template_name='signup.html'), name="start-signup"),
        url(r'^change-password/$', change_password, name="change-password"),
        url(r'^howitworks$', TemplateView.as_view(template_name= 'how.html'), name='how-it-works'),
        url(r'^who-we-are/$', TemplateView.as_view(template_name='about.html'), name='about'),
        url(r'^pricing$', TemplateView.as_view(template_name='pricing.html'), name='pricing'),
        url(r'^account_activation_sent/$', activation_sent, name='account_activation_sent'),
        url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .forms import *
from .views import (StudentListView, student_profile, request_help,
                    export_excel, create_student, update_photo, student_chart_json,
                    mapper_excel_generator, generate, generate_mapper_json,
                    edit_profile, StudentAnalyticsView, import_student_data, upload_student_csv)
urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^analysis/$', login_required(StudentAnalyticsView.as_view()), name='student_analytics'),
    url(r'^new_student/$', create_student, name='create_student'),
    url(r'^profile/(?P<student_slug>[\w-]+)/$', student_profile , name='student_account'),
    url(r'^excel/$', export_excel, name='export_excel'),
    url(r'^mapper/$', mapper_excel_generator, name='mapper'),
    url(r'^update-profile/$', edit_profile, name='edit-profile'),
    url(r'^mapper/generator/$', generate, name='generate'),
    url(r'^update-photo/$', update_photo, name='update_photo'),
    url(r'^student-json/$', student_chart_json, name='student_chart_json'),
    url(r'^mapper-json/$', generate_mapper_json, name='mapper-json'),
    url(r'^ineed/assistance/(?P<student_id>\d+)/$', request_help , name='help'),
    url(r'^bulk-upload/$', import_student_data , name='student-import'),
    url(r'^upload/$', upload_student_csv , name='student-upload'),

)

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from students.models import Student
from institutions.models import Department 
from staff.models import Lecturer
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class Course(models.Model):
    SEMESTER_CHOICES = (
    (1, 'First Semester'),
    (2, 'Second Semester'),
    )
    course_code = models.CharField(max_length=7, null=True)
    name = models.CharField(max_length=250, null=True)
    unit = models.PositiveIntegerField(default=0, verbose_name="Number of credit units")
    level = models.IntegerField(choices=settings.LEVEL_CHOICES, null=True)
    semester = models.IntegerField(choices=SEMESTER_CHOICES, null=True)
    department = models.ForeignKey(Department, null=True)
    lecturers = models.ManyToManyField(Lecturer, help_text="Hold down the control key and select more than one lecturer",  blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_modified = models.DateTimeField(auto_now=True, null=True)
    added_by = models.ForeignKey(User)
    

    class Meta:
        verbose_name = _(u'Course Available')
        verbose_name_plural = _(u'Courses Available')
        ordering = ('level',)

    def __str__(self):
        return '%s: %s' % (self.course_code, self.name)


class CourseRegistration(models.Model):
    SEMESTER_CHOICES = (
    (1, 'First Semester'),
    (2, 'Second Semester'),
    )

    student = models.ForeignKey(Student, null=True)
    level = models.PositiveIntegerField(choices=settings.LEVEL_CHOICES, null=True)
    semester = models.PositiveIntegerField(choices=SEMESTER_CHOICES, null=True)
    session = models.CharField(max_length=15, null=True)
    course = models.ForeignKey(Course, null=True)
    carried_over = models.NullBooleanField(default=False)
    department = models.ForeignKey(Department, null=True)
    date_created = models.DateField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = _(u'Course Registered')
        verbose_name_plural = _(u'Courses Registered')
        ordering = ('level',)

    def __str__(self):
        return "%s" % (self.course)




# Create your models here.

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class Category(models.Model):
	name = models.CharField(max_length=50)

	class Meta:
		verbose_name = _(u'Forum Category')
		verbose_name_plural = _(u'Forum Categories')
		ordering = ('name',)

	def __str__(self):
		return self.name

	def last_post(self):
		if self.post_set.count():
			return self.post_set.order_by("created")[0]


class Post(models.Model):
	POST_CHOICES = (
		('Q', 'Question'),
		('I', 'Idea')
	)
	user = models.ForeignKey(User)
	title = models.CharField(max_length=50)
	post_type = models.CharField(max_length=1, choices=POST_CHOICES)
	category = models.ForeignKey(Category)
	question_or_idea = models.TextField(_(u'Your question or Idea to Share'), 
						help_text="Make your post as clear as possible for quick feedback")
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = _(u'Post')
		verbose_name_plural = _(u'Posts')

	def __str__(self):
		return self.title


class Response(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	comment = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-date_created',)

	def __str__(self):
		return "%s - %s" % (self.user.last_name, self.comment[:20])


class Reply(models.Model):
	user = models.ForeignKey(User)
	response = models.ForeignKey(Response)
	comment = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.comment[:20]

class ProfaneWord(models.Model):
    word = models.CharField(max_length=60)

    def __str__(self):
        return self.word

courses/views.py
from django.shortcuts import render
from django.db import transaction
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from courses.models import Course
from .forms import *
from django.forms.models import modelformset_factory
from django.forms.formsets import formset_factory
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView
from django.utils.translation import ugettext as _
from institutions.models import Department
from staff.models import Lecturer
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

class CourseListView(ListView):
    model = Course
    template_name = 'courses/all.html'
    paginated_by = settings.PAGE_SIZE

    def get_queryset(self):
        queryset = Course.objects.filter(added_by=self.request.user)

        params = self.request.GET
        level = params.get('level')
        department = params.get('department')

        if level !="all" and level is not None:
            queryset = queryset.filter(level=level)
        if department != "all" and department is not None:
            queryset = queryset.filter(department_id=department)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CourseListView, self).get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginated_by)

        page = self.request.GET.get('page')

        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        context['courses'] = queryset
        return context


class RegisteredCourseView(ListView):
    model = CourseRegistration
    template_name = 'courses/registered_courses.html'
    context_object_name = 'reg_courses'
    paginated_by = settings.PAGE_SIZE

    def get_queryset(self):
        queryset = CourseRegistration.objects.filter(student=self.request.user.student).order_by('level', 'semester')
        params = self.request.GET
        level = params.get('level', 'all')
        semester = params.get('semester', 'all')

        if level != 'all':
            queryset = queryset.filter(level=level)
        if semester != 'all':
            queryset = queryset.filter(semester=semester)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(RegisteredCourseView, self).get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginated_by)

        page = self.request.GET.get('page')

        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        context['reg_courses'] = queryset
        return context
        

@transaction.atomic
@login_required
@user_passes_test(lambda u: hasattr(u, 'lecturer') and u.lecturer.is_admin, login_url='/login/')
def new_course(request):
    if request.method == 'POST':
        params = request.POST
        course_code = params.get('course_code', '')
        name = params.get('name', '')
        unit = params.get('unit', '')
        dept_id = params.get('department', '')
        semester = params.get('semester', '')
        level = params.get('level', '')
        lecturers = params.getlist('lecturer', '')
        department = Department.objects.get(pk=dept_id)
        try:
            pay_load = {
                'course_code': course_code,
                'name': name,
                'unit': unit,
                'department': department,
                'level': level,
                'semester': semester,
            }
            course = Course(**pay_load)
            course.added_by = request.user
            course.save()
            for i in lecturers:
                lecturer = Lecturer.objects.get(pk=int(i))
                course.lecturers.add(lecturer)
            course.save()
            import pdb
            pdb.set_trace()
            messages.success(request, "The course: '%s: %s', has been successfully created" %(course.course_code, course.name))
        except Exception as e:
            messages.error(request, e)
    return HttpResponseRedirect(reverse('courses:course-list'))

@login_required
@user_passes_test(lambda u: hasattr(u, 'student'))
@transaction.atomic
def reg_course(request):
    extra = 1
    CourseRegFormset = formset_factory(BatchCourseForm, extra=extra)
    if request.method == 'POST':
        batch_formset = CourseRegFormset(request.POST)
        static_form = CourseRegistrationForm(request.POST)
        if static_form.is_valid() and batch_formset.is_valid():
            try:
                existing = 0
                saved = 0
                for form in batch_formset:
                    course = form.save(commit=False)
                    course.student = request.user.student
                    course.level = static_form.cleaned_data['level']
                    course.department = request.user.student.department
                    if CourseRegistration.objects.filter(course=course.course, student=course.student, session=course.session).exists() and not course.carried_over:
                        existing += 1
                    else:
                        course.save()
                        saved += 1
                messages.success(request, "You successfully registered %s courses.\
                                 %s failed because they already exist" % (saved, existing))
                return HttpResponseRedirect(reverse('courses:reg_course'))
            except Exception as e:
                messages.error(request, e)
    else:
        batch_formset = CourseRegFormset()
        static_form = CourseRegistrationForm()
    context = {
            'static_form': static_form,
            'batch_formset': batch_formset
        }

    return render(request, 'courses/reg_course.html', context)

@login_required
@user_passes_test(lambda u: hasattr(u, 'lecturer') and u.lecturer.is_admin, login_url='/login/')
def edit_course(request, course_id):
    template_name = 'courses/edit_course.html'
    course = Course.objects.get(pk=course_id)
    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, "The course '%s' was successfully updated" % (course))
            return HttpResponseRedirect(reverse('courses:course-list'))
    else:
        form = CourseForm(instance=course)
    return render(request, template_name, {'form': list(form), 'course': course})

courses/templates/courses/all.html
{% extends 'dashboard.html' %}
{% load staticfiles record_filters %}

{% block title %}Staff{% endblock %}
    
{% block breadcrumbs %}
<a href="{% url 'students:students_list' %}">All Courses</a>
{% endblock %}
{% block content %}
    <div id="query_result" class="row"></div>
    <div style="margin-bottom: 30px;">
       <h3 class="page-header">All Available Courses <span style="float: right;"><a href="#modal-course" data-toggle='modal'><button class="btn btn-sm custom-btn"><i class="icons icons-sm icons-plus" data-toggle='modal'></i> Add New...</button></a></span></h3>
    </div>
    <div>
        {% block heading %}{% endblock %}
        <table class='table table-condensed table-hover'>
            <thead>
                <tr>
                    <th scope="col" style="width: 6%">&nbsp;</th>
                    <th style="width: 15%;">Course Code</th>
                    <th style='width: 35%;'>Course Title</th>
                    <th style='width: 25%;'>Department</th>
                    <th>Semester</th>
                    <th style='width: 7%;'>Lecturers</th>
                    <th style='width: 20%; text-align: center;'>Action</th>
                </tr>
            </thead>
            <tbody>
            {% if courses %}
                {% for course in courses %}
                <tr class="{% ifchanged course.level %} section-group{% endifchanged %}">
                   <td style="font-size: 1.4em; padding-top: 0px;"><strong>
                    {% ifchanged %}{{ course.level }}{% endifchanged %}</strong>
                    </td>
                    <td><a href="#" style="text-decoration: none;">{{ course.course_code }}</a></td>
                    <td>{{ course.name }}</td>
                    <td>{{ course.department }}</td>
                    <td>{{course.semester}}</td>
                    <td style="text-align: center;">
                        <div class='dropdown'>
                                <button class='btn btn-sm custom-btn dropdown-toggle' data-toggle='dropdown' class=""><i class="icons icons-sm icons-slider"></i> See Lecturers</button>
                            <ol class='dropdown-menu' role="menu" style="left: -25px; border-top: 2px solid #2c3e50; background-color: #fefefe; padding-left: 10px;">
                                {% for lecturer in course.lecturers.all %}
                                <li>{{lecturer}}</li>
                                {% endfor %}
                            </ol>
                        </div>
                    </td>
                    <td><button class="btn btn-sm custom-btn" onclick="location.href='{% url 'courses:edit' course_id=course.id %}'"><i class="icons icons-sm icons-edit" style="font-weight: normal;"></i> Edit</button></td>
                </tr>
                {% endfor %}
                {% else %}
                <tr><td colspan="7" style="text-align: center; font-size: 20px; font-weight: 600;">No Records Found</td></tr>
            {% endif %}
            </tbody>
        </table>
    </div>
    <div>
        {% render_paginator courses %}
    </div>
{% endblock content %}

{% block side%}
<div class="panel panel-default" style="min-height: 200px; margin-top: 5px;">
    <div class="panel-body">
        <div class="sub-panel">
            <h4><strong>Query Filter</strong></h4>
        </div>
        <form action="">
            <div class="form-group">
                <label for="id_level">By Level:</label>
                <select name="level" class="form-control input-sm" id="id_level">
                <option value="all">Select Level</option>
                <option value="100">100 Level</option>
                <option value="200">200 Level</option>
                <option value="300">300 Level</option>
                <option value="400">400 Level</option>
                <option value="500">500 Level</option>
                <option value="600">600 Level</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_department">By Department:</label>
                <select name="department" id="id_department" class="form-control input-sm">
                    <option value="all">Select Department</option>
                    {% for department in departments %}
                    <option value="{{department.id}}">{{department}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-sm custom-btn" type="search">Filter Queryset</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block extrajs %}
    <script>
        
    </script>
    <script>
       function change() {
        var frm = document.getElementById("status_form");
            frm.submit(function(e) {
                e.preventDefault();
                $.get("/students/", function(response) {
                    console.log(response);
                });
            });

        }
    </script>
{% endblock extrajs %}

courses/templates/courses/course_create.html
{% load staticfiles %}

  <div class="modal-dialog" style="padding: 10px;">
    <!-- Modal content-->
    <div class="modal-content">
    <form method="post" action="{% url 'courses:create_course' %}">{% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title"><strong>New Course</strong></h3>
      </div>
      <div class="modal-body">
         <div class="form-group">
           <label for="id_course_code">Course Code</label>
           <input type="text" class="form-control text-input" name="course_code" placeholder="Course Code">
         </div>
         <div class="form-group">
           <label for="id_name">Course Title</label>
           <input type="text" class="form-control text-input" name="name" placeholder="Course Title">
         </div>
         <div class="form-group">
           <label for="id_unit">Credit Load</label>
           <input type="number" class="form-control" placeholder="Credit Load" id="id_unit" name="unit">
         </div>
         <div class="form-group">
           <label for="id_department">Department</label>
           <select name="department" id="id_department" class="form-control">
              <option value="">Select ...</option>
             {% for department in departments %}
             <option value="{{department.id}}">{{department}}</option>
             {% endfor %}
           </select>
         </div>
         <div class="form-group">
           <label for="id_level">Level</label>
           <select name="level" id="id_level" class="form-control">
              <option value="">Select ...</option>
             <option value="100">100 Level</option>
             <option value="200">200 Level</option>
             <option value="300">300 Level</option>
             <option value="400">400 Level</option>
             <option value="500">500 Level</option>
             <option value="600">600 Level</option>
           </select>
         </div>
         <div class="form-group">
           <label for="id_semester">Semester</label>
           <select name="semester" id="id_semester" class="form-control">
             <option value="">Select ...</option>
             <option value="1">First Semester</option>
             <option value="2">Second Semester</option>
           </select>
         </div>
         <div class="form-group">
           <label for="id_lecturer">Lecturers <span><small>[Hold control and select, to choose multiple lecturers]</small></span></label>
           <select multiple name="lecturer" id="id_lecturer" class="form-control">
             {% for lecturer in lecturers %}
             <option value="{{lecturer.id}}">{{lecturer}}</option>
             {% endfor %}
           </select>
         </div>
      </div>
      <div class="modal-footer">
        <div class="form-group">
            <button class="btn custom-btn btn-sm" type="submit">Create</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
        </div>
      </div>
    </form>
    </div>
  </div>

courses/templates/courses/edit_course.html
{% extends 'dashboard.html' %}

{% load staticfiles %}
{% load form_tags %}

{% block content %}
  <div class="col-md-10 center-block">
    <h3 class="page-header">Edit {{course}}</h3>
    <div class="sub-panel add-padding alert alert-info" style="font-size: 15px;">
        <p><strong>NOTE:</strong> Please be informed that changing the course information will affect other records in the database. If you are not sure of what you're doing, contact a <strong>Grade-X Expert</strong> for assistance.</p>
    </div>
    <form class="form-horizontal" method="post" >{% csrf_token %}
      <div class="col-md-5" style="margin-right: 10px;">
        {% for field in form|slice:":4" %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field}}
        </div>
        {% endfor %}
      </div>
      <div class="col-md-5" style="margin-left: 10px;">
        {% for field in form|slice:"4:" %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {% if field.html_name == 'lecturers' %}<p class="alert-success"><strong>Hint:</strong> [{{field.help_text}}]</p>{% endif %}
          {{field}}
        </div>
        {% endfor %}
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <button class="btn btn-sm custom-btn" type="submit">Save Changes</button>
        </div>
      </div>
    </form>
</div>
{% endblock %}

 {% block extrajs %}{% endblock %}  

courses/templates/courses/registered_courses.html
{% extends 'dashboard.html' %}
{% load record_filters %}
{% block breadcrumbs %}
    <a> Registered Courses</a> &raquo;
{% endblock %}

{% block content %}
    <div style="margin-bottom: 30px;">
        <h3 class="page-header">Your Registered Courses <span style="float: right;"><button class="btn btn-sm custom-btn" onclick="location.href='{% url 'courses:reg_course' %}'">Register New Courses</button></span> </h3>
    </div>
<div class='container-fluid '>
    {% if reg_courses %}
    <table class='table table-condensed'>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th scope="col" style="width: 7%">S/N</th>
                <th style="width: 30%;">Course</th>
                <th>Semester</th>
                <th>Level</th>
                <th>Carried Over</th>
                <th style="width: 15%;">Date</th>
            </tr>
        </thead>
        <tbody>
            {% for course in reg_courses %}
                <tr class="{% ifchanged course.level %} section-group{% endifchanged %}">
                <td style="font-size: 1.4em; padding-top: 0px;"><strong>
                {% ifchanged %}{{ course.level }}{% endifchanged %}</strong>
                </td>
               <td>{{forloop.counter}}</td>
                <td style="width: 40%;">{{ course }}</td>
                <td>{{ course.semester }}</td>
                <td>{{ course.level }}</td>
                <td>{{ course.carried_over }}</td>
                <td style="width: 7%; text-align: left;">{{ course.date_created }}</td>
            </tr>
            {% endfor %} 
        </tbody>
    </table>
    {% else %}
    <div style="text-align: center; color: #2c3e50; margin: 10% auto;">
        <i class="icons icons-x-lg icons-table"></i><br>
        <h3>No Registered Courses Yet. It appears {% if user.lecturer %}this is {% else %} you're {% endif %} a Rookie</h3>
        <h5>You can explore other features of grade-X <a href=""><u>HERE</u></a></h5>
    </div>
    {% endif %}
    <div>
      {% render_paginator reg_courses %}  
    </div>
</div>
{% endblock %}

{% block side %}
<div class="panel panel-default" style="min-height: 200px; margin-top: 5px;">
    <div class="panel-body">
        <div class="sub-panel">
            <h4><strong>Query Filter</strong></h4>
        </div>
        <form action="">
            <div class="form-group">
                <label for="id_level">By Level:</label>
                <select name="level" class="form-control input-sm" id="id_level">
                <option value="all">Select Level</option>
                <option value="100">100 Level</option>
                <option value="200">200 Level</option>
                <option value="300">300 Level</option>
                <option value="400">400 Level</option>
                <option value="500">500 Level</option>
                <option value="600">600 Level</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_category">By Semester:</label>
                <select name="semester" id="id_semester" class="form-control input-sm">
                    <option value="all">Select Semester</option>
                    <option value="1">First Semester</option>
                    <option value="2">Second Semester</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-sm custom-btn" type="search">Filter Queryset</button>
            </div>
        </form>
    </div>
</div>

{% include '_trending.html' %}
{% endblock %}