analyzer/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^plots/(?P<student_slug>[\w-]+)$', student_analysis, name='all_results_plot'),
    url(r'^cgpa/(?P<student_slug>[\w-]+)/analysis/$', student_cgpa_analysis, name='cgpa_analysis'),
    url(r'^filtered/(?P<student_slug>[\w-]+)/$', filter_data, name='filtered_plot'),
    url(r'^by_level/(?P<student_slug>[\w-]+)$', cgpa_by_level, name='cgpa_by_level'),
    url(r'^$', analytics_main, name='main_analysis_page'),
    url(r'^analsis/course/(?P<student_slug>[\w-]+)/$', course_analysis, name='course_analysis'),
    url(r'^all/$', all_analysis, name='all_analysis'),
    url(r'^predict/(?P<student_slug>[\w-]+)/$', prediction, name='prediction'),
    url(r'^predict/result/(?P<student_slug>[\w-]+)/$', make_prediction, name='make_prediction'),
    url(r'^excel/$', export_excel, name='export_excel'),
    url(r'^workspace/$', workspace, name='workspace'),
)

assignments/urls.py
from django.conf.urls import patterns, url
from .views import (deactivate, AssignmentScoreListView, 
					assignment_detail, create_assignment, 
					AssignmentView, submit_assignment, 
					score_sheet, mark)

urlpatterns = patterns("",
	url(r'^all-assignments/$', AssignmentScoreListView.as_view(), name='all_assignments'),
	url(r'^create/$', create_assignment, name='create_assignment'),
	url(r'^list/$', AssignmentView.as_view(), name='staff_assignments'),
	url(r'^details/(?P<assignment_code>[\w-]+)/$', assignment_detail, name='assignment_detail'),
	url(r'^submit/(?P<assignment_code>[\w-]+)/$', submit_assignment, name='submit_assignment'),
	url(r'^deactivate/(?P<assignment_id>\d+)/$', deactivate, name='deactivate'),
	url(r'^score-sheet/(?P<assignment_id>\d+)/$', score_sheet, name='score-sheet'),
	url(r'^marked/(?P<assignment_id>\d+)/$', mark, name='marked'),
)

core/urls.py
from .views import setup, activate, update_quote, check_user
from django.conf.urls import patterns, url


urlpatterns = patterns('', 
	url(r'^setup/$', setup, name='user-settings'),
	url(r'^activate/$', activate, name='activate'),
	url(r'^update_quote/$', update_quote, name='update_quote'),
	url(r'^check/$', check_user, name='check_user'),

)

courses/urls.py
from django.conf.urls import patterns, url
from .views import new_course, reg_course, CourseListView, edit_course, RegisteredCourseView

urlpatterns = patterns('',
    url(r'^create_course/$', new_course, name='create_course'),
    url(r'^edit/(?P<course_id>\d+)/$', edit_course, name='edit'),
    url(r'^reg/$', reg_course, name='reg_course'),
    url(r'^registered/$', RegisteredCourseView.as_view(), name='course-registered'),
    url(r'^list$', CourseListView.as_view(), name='course-list')
)

result_analytics/urls.py
"""result_analytics URL Configuration
"""

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 
from result_analytics.views import index, home, register_user, register_success
from django.views.static import serve
from .views import home, change_password, activation_sent, activate

urlpatterns = [ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^assignments/', include('assignments.urls', namespace='assignment')),
    url(r'^$', index, name='user_index'),
    url(r'^prompt$', TemplateView.as_view(template_name='_signup_prompt.html'), name='signup-prompt'),
    url(r'^dashboard/$', home, name='dashboard'),
    url(r'^results/', include('results.urls', namespace='results')),
    url(r'^analytics/', include('analyzer.urls', namespace='analyzer')),
    url(r'^staff/', include('staff.urls')),
    url(r'^setup/', include('core.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^notification/', include('notifications.urls', namespace='notifications')),
    url(r'^institution/', include('institutions.urls', namespace='institution')),
    url(r'^collaborate/', include('collaborations.urls', namespace="collaborate")),
    url(r'^forum/', include('forum.urls')),
]
urlpatterns+=patterns('django.contrib.auth.views',
        url(r'^login/$', 'login', {'template_name': 'login.html'}, name='result_login'),
        url(r'^password-reset/$', 'password_reset', {
            'template_name': 'password_reset.html',
            'email_template_name': 'password_reset_email.html',
            'subject_template_name':'password_reset_subject.txt',
            'post_reset_redirect': ('result_reset_done'),
            'html_email_template_name':'password_reset_email.html',
            }, name="result_password_reset"),
        url(r'^password-reset-done/$', 'password_reset_done', {'template_name':'password_reset_done.html',}, name="result_reset_done"),
        url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'password_reset_confirm',{'template_name':'password_reset_confirm.html',}, name="photobox_reset_confirm"),
        url(r'^password-reset-complete/$', 'password_reset_complete',{'template_name':'password_reset_complete.html',}, name="result_reset_complete"), 
        url(r'^logout/$', 'logout', {'next_page': 'result_login'}, name="result_logout"),
)

urlpatterns+=patterns('',
        url(r'^successful/$', register_success, name="result_success"),
        url(r'^signup/$', register_user, name="result_signup"),
        url(r'^start/signup/$', TemplateView.as_view(template_name='signup.html'), name="start-signup"),
        url(r'^change-password/$', change_password, name="change-password"),
        url(r'^howitworks$', TemplateView.as_view(template_name= 'how.html'), name='how-it-works'),
        url(r'^who-we-are/$', TemplateView.as_view(template_name='about.html'), name='about'),
        url(r'^pricing$', TemplateView.as_view(template_name='pricing.html'), name='pricing'),
        url(r'^account_activation_sent/$', activation_sent, name='account_activation_sent'),
        url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

results/urls.py
from django.conf.urls import patterns, url
from .views import (
                add_result, result_list,
                upload_csv, grading_setting, result_by_student, 
                import_data, export_excel, full_detail, 
                overall_result, StaffBasedResultView, edit_result
                )

urlpatterns = patterns('',
    url(r'^add_results/$', add_result, name='add_result'),
    url(r'^edit-result/$', edit_result, name='edit_result'),
    url(r'^grading-scheme$', grading_setting, name='grading-setting'),
    url(r'^upload_csv/$', upload_csv, name='upload_csv'),
    url(r'^lecturer-results/$', StaffBasedResultView.as_view(), name='staff_result'),
    url(r'^import_results/$', import_data, name='result_import'),
    url(r'^students_import/$', import_data, name='student_import'),
    url(r'^$', result_list, name='students_results'),
    url(r'^own_results/(?P<student_slug>[\w-]+)/$', result_by_student, name='personal_results'),
    url(r'^overall_results/(?P<student_slug>[\w-]+)/$', overall_result, name='all_results'),
    url(r'^(?P<student_slug>[\w-]+)/result_details/$', full_detail, name='full_detail'),
    url(r'^excel/$', export_excel, name='export_excel'),
)

students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .forms import *
from .views import (StudentListView, student_profile, request_help,
                    export_excel, create_student, update_photo, student_chart_json,
                    mapper_excel_generator, generate, generate_mapper_json,
                    edit_profile, StudentAnalyticsView, import_student_data, upload_student_csv)
urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^analysis/$', login_required(StudentAnalyticsView.as_view()), name='student_analytics'),
    url(r'^new_student/$', create_student, name='create_student'),
    url(r'^profile/(?P<student_slug>[\w-]+)/$', student_profile , name='student_account'),
    url(r'^excel/$', export_excel, name='export_excel'),
    url(r'^mapper/$', mapper_excel_generator, name='mapper'),
    url(r'^update-profile/$', edit_profile, name='edit-profile'),
    url(r'^mapper/generator/$', generate, name='generate'),
    url(r'^update-photo/$', update_photo, name='update_photo'),
    url(r'^student-json/$', student_chart_json, name='student_chart_json'),
    url(r'^mapper-json/$', generate_mapper_json, name='mapper-json'),
    url(r'^ineed/assistance/(?P<student_id>\d+)/$', request_help , name='help'),
    url(r'^bulk-upload/$', import_student_data , name='student-import'),
    url(r'^upload/$', upload_student_csv , name='student-upload'),

)

analyzer/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from institutions.models import Department
from results.models import Result

class Actvity(models.Model):
    activity_name = models.CharField(max_length=100, null=True)
    department = models.ForeignKey(Department)
    results = models.ForeignKey(Result)
    date_created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = _(u'Analysis Activity')
        verbose_name_plural = _(u'Analysis Activities')
        ordering = ('date_created',)
        
    def __str__(self):
        return self.activity_name

# Create your models here.

analyzer/templates/analyzer/_all_results.html
{% extends 'dashboard.html' %}
{% load staticfiles %}

{% block extrahead%}
  
{% endblock %}

{% block breadcrumbs %}
{% if user.is_staff %}<a href="{% url 'students:students_list' %}">All students &raquo;</a>{% endif %} {{ student }}'s Analysis
{% endblock %}

{% block content %}
    <div class="row clearfix" style="margin-left: 10px; margin-bottom: 20px;">
        <h3 class="page-header">{{ student.reg_number }} - Analysis Breakdown</h3>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default" style="margin-left: 20px; width: 98%;">
                <div class="panel-heading">Current Level Result Performance</div>
                <div class="panel-body">
                    <div id="{{ chartID|safe }}">
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success" style="width: 98%;">
                <div class="panel-heading">Overall Result Performance of Previous Levels</div>
                <div class="panel-body">
                    <div id="chart">
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-danger" style="margin: 10px 20px 35px 35px;">
            <div class="panel-heading">Average Aggregate Analysis</div>
            <div class="panel-body">
                <div id="overall-chart">
                  
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    
    <script>
        var chart_id = {{ chartID|safe }}
        var chart = {{ chart|safe }}
        var xAxis = {{ xAxis|safe }}
        var yAxis = {{ yAxis|safe }}
        var series = {{ series|safe }}
        var title = {{ title|safe }}
        var o_chart = {{ o_chart|safe }}
        var o_xAxis = {{ o_xAxis|safe }}
        var o_yAxis = {{ o_yAxis|safe }}
        var o_series = {{ o_series|safe }}
        var o_title = {{ o_title|safe }}
        var v_chart = {{ v_chart|safe }}
        var v_xAxis = {{ v_xAxis|safe }}
        var v_yAxis = {{ v_yAxis|safe }}
        var v_series = {{ v_series|safe }}
        var v_title = {{ v_title|safe }}
    </script>
    <script>
      $(function () {
    $('#overall-chart').highcharts({
        chart: v_chart,
        title: v_title,
        xAxis: v_xAxis,
        yAxis: v_yAxis,
        series: v_series
    });
    
    $('#chart').highcharts({
        chart: o_chart,
        title: o_title,
        xAxis: o_xAxis,
        tooltip: {
            valueSuffix: '%',
        },
        yAxis: o_yAxis,
        series: o_series
    });
    
    $(chart_id).highcharts({
        chart: chart,
        title: title,
        xAxis: xAxis,
        yAxis: yAxis,
        series: series
    });
});
        
    </script>
{% endblock %}

analyzer/templates/analyzer/_analyze_cgpa.html
{% extends 'staff/dashboard.html' %}
{% load staticfiles %}

{% block extrahead%}
  
{% endblock %}

{% block side_panel %}
    
{% endblock %}

{% block breadcrumbs %}
{% if user.is_staff %}<a href="{% url 'students:students_list' %}">All students &raquo;</a>{% endif %} {{ student }}'s CGPA Analysis
{% endblock %}

{% block inner_content %}
    <div>
        <h3 class="page-header"> {{ student }}'s CGPA Details</h3>
    </div>
    <div class="row">
        <div class="panel panel-danger" style="margin: 10px 20px 35px 35px;">
            <div class="panel-heading">CGPA Analysis</div>
            <div class="panel-body">
                <div id="{{ chartID }}">
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
       <div class="panel panel-default" style="margin: 10px 20px 35px 35px;">
           <div class="panel-heading">Other Analysis</div>
           <div class="panel-body">
               <div id="chart">
                   
               </div>
           </div>
       </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    
    <script>
        var chart_id = {{ chartID|safe }}
        var chart = {{ chart|safe }}
        var xAxis = {{ xAxis|safe }}
        var yAxis = {{ yAxis|safe }}
        var series = {{ series|safe }}
        var title = {{ title|safe }}
    </script>
    <script>
      $(function () {
    $(chart_id).highcharts({
        chart: chart,
        title: title,
        xAxis: xAxis,
        yAxis: yAxis,
        series: series
    });
});
        
    </script>
{% endblock %}

analyzer/templates/analyzer/_analyze_school.html
<div class="panel panel-primary">
    <div class="panel-heading">School Analysis</div>
    <div class="panel-body row">
        <div class="col-sm-8 col-xs-8 col-md-9">
          
        </div>
        <div class="col-sm-4 col-xs-4 col-md-3">
    
            <div class="text-center">
              
            </div>
    
        </div>
    </div>
</div>

analyzer/templates/analyzer/_by_level.html
{% extends'dashboard.html' %}
{% load staticfiles %}

{% block extrahead%}
  
{% endblock %}

{% block side_panel %}
    
{% endblock %}

{% block breadcrumbs %}CGPA Analysis
{% endblock %}

{% block content %}
    <div>
        <h3 class="page-header"> {{ student }}'s CGPA Details</h3>
    </div>
    <div class="row">
        <div class="panel panel-danger" style="margin: 10px 20px 35px 35px;">
            <div class="panel-heading">CGPA Analysis</div>
            <div class="panel-body">
                <div id="{{ chartID }}">
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    
    <script>
        var chart_id = {{ chartID|safe }}
        var chart = {{ chart|safe }}
        var xAxis = {{ xAxis|safe }}
        var yAxis = {{ yAxis|safe }}
        var series = {{ series|safe }}
        var title = {{ title|safe }}
    </script>
    <script>
      $(function () {
    $(chart_id).highcharts({
        chart: chart,
        title: title,
        xAxis: xAxis,
        yAxis: yAxis,
        series: series
    });
});
        
    </script>
{% endblock %}

analyzer/templates/analyzer/analytics_main.html
{% extends 'dashboard.html' %}
{% load staticfiles %}

{% block extrahead%}
  
{% endblock %}

{% block breadcrumbs %}
    <a href="{% url 'analyzer:all_analysis' %}">Analytics &raquo;</a>
{% endblock %}
{% block content %}
    <div class="row clearfix" style="margin-left: 10px; margin-bottom: 20px;">
        <h3 class="page-header">Analytics Dashboard</h3>
    </div>
    <div class="row" style='margin-left: 0px; margin-bottom: 10px;'>
        <a href="{% url 'students:students_list' %}" class="menu-anchor">
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>All Students</h4>
            <div style="font-size: 1.5em;">
                 {{ all_students.count }}
            </div>
        </div></a>
        <a href="{% url 'students:students_list' %}?status=A" class="menu-anchor">
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>Active Student </h4>
            <div style="font-size: 1.5em;">
                 {{ total }}
            </div>
        </div></a>
        <a href="{% url 'students:students_list' %}?status=S" class="menu-anchor">
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>On Suspension</h4>
            <div style="font-size: 1.5em;">
                {{ suspension }}
            </div>
        </div></a>
        <a href="{% url 'students:students_list' %}?status=G" class="menu-anchor">
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>Graduated</h4>
            <div style="font-size: 1.5em;">
                 {{ graduated }}
            </div>
        </div></a>  
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>Males</h4>
            <div style="font-size: 1.5em;">
                {{ males }}
            </div>
        </div>
        <div class="col-md-2 col-sm-6 col-xs-6 info">
            <h4>Females</h4>
            <div style="font-size: 2em;">
                {{ females }}
            </div>
        </div>
    </div>
    <div class="col-md-12 mobile-pad">
        <div class="panel panel-info analytics">
            <div class="panel-heading">Active Students' GPAs </div>
            <div class="panel-body">
                 <div id="all_gpa">
                     
                 </div>
            </div>
        </div> 
    </div>
    <div class="col-md-12 mobile-pad">
        <div class="panel panel-success analytics">
            <div class="panel-heading">Graduate Students' GPAs </div>
            <div class="panel-body">
                 <div id="g_charts">
                     
                 </div>
            </div>
        </div> 
    </div>
    <div class="col-md-12 mobile-pad">
        <div class="panel panel-info analytics" style="margin-left: 0px;">
            <div class="panel-heading">Yearly Performance</div>
            <div class="panel-body">
                <div id='chart_avg' style="background: #fff; ">
    
                </div>
            </div>
        </div>
        
    </div>
    <div class="col-md-12 mobile-pad">
        <div class="panel panel-default analytics">
            <div class="panel-heading">Course Average Performance</div>
            <div class="panel-body">
                 <div id='c_chart'>
                    
                 </div>
            </div>
        </div> 
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    
    <script>
        var cgpa_chart = {{ cgpa_chart|safe }}
        var cgpa_xAxis = {{ cgpa_xAxis|safe }}
        var cgpa_yAxis = {{ cgpa_yAxis|safe }}
        var cgpa_series = {{ cgpa_series|safe }}
        var cgpa_title = {{ cgpa_title|safe }}
        var chart = {{ chart|safe }}
        var xAxis = {{ xAxis|safe }}
        var yAxis = {{ yAxis|safe }}
        var series = {{ series|safe }}
        var title = {{ title|safe }}
        var c_chart = {{ c_chart|safe }}
        var c_xAxis = {{ c_xAxis|safe }}
        var c_yAxis = {{ c_yAxis|safe }}
        var c_series = {{ c_series|safe }}
        var c_title = {{ c_title|safe }}
        var g_chart = {{ g_chart|safe }}
        var g_xAxis = {{ g_xAxis|safe }}
        var g_yAxis = {{ g_yAxis|safe }}
        var g_series = {{ g_series|safe }}
        var g_title = {{ g_title|safe }}
    </script>
    <script>
      $(function () {
    $('#all_gpa').highcharts({
        chart: cgpa_chart,
        title: cgpa_title,
        xAxis: cgpa_xAxis,
        yAxis: cgpa_yAxis,
        series: cgpa_series
    });
    
    $('#chart_avg').highcharts({
        chart: chart,
        title: title,
        xAxis: xAxis,
        yAxis: yAxis,
        series: series
    });
    $('#c_chart').highcharts({
        chart: c_chart,
        title: c_title,
        xAxis: c_xAxis,
        yAxis: c_yAxis,
        series: c_series
    });
    
    $('#g_charts').highcharts({
        chart: g_chart,
        title: g_title,
        subtitle: {text: "Graduate Students' records "},
        xAxis: g_xAxis,
        yAxis: g_yAxis,
        series: g_series
    });
});
        
    </script>
{% endblock %}

analyzer/templates/analyzer/attached.html
{% load staticfiles %}

    <h4><i class="icons icons-md icons-dashboard"></i> Dashboard</h4>
{% if user.lecturer.is_admin %}
    <li><a href="{% url 'students:students_list' %}"><i class="icons icons-sm icons-group"></i> All Students <span class="badge"> {{ all_students.count }}</span></a></li>
    <li><a href="{% url 'students:create_student' %}"><i class="icons icons-sm icons-new-user"></i> New Student </a></li>
    <li><a href="{% url 'students:student-import' %}"><i class="icons icons-sm icons-new-user"></i> Bulk Student Upload </a></li>
    <li><a href="{% url 'results:students_results' %}">All Students Results <span class="badge"> {{ all_results.count }}</span></a></li>
    <li><a href="{% url 'staff-list' %}">Employee List <span class="badge"> {{lecturers.count}}</span></a></li>
    <li><a href="{% url 'new-staff' %}"><i class="icons icons-sm icons-new-user"></i> New Staff </a></li>
    <li><a href="{% url 'courses:course-list' %}"><i class="icons icons-sm icons-list"></i> All Courses <span class="badge"> {{ all_courses.count }}</span></a></li>
    <li><a href="{% url 'results:grading-setting' %}"><i class="icons icons-sm icons-tasks"></i> Grading Setup </a></li>
{% endif %}
{% if user.is_staff and student %}
    <h4><i class="icons icon-md icons-user-alt"></i> Student Analysis</h4>
    <li><a href="{% url 'students:student_account' student.slug %}"><i class="icons icons-sm icons-user"></i> {{ student}}'s Profile</a></li>
    <li><a href="{% url 'results:personal_results' student.slug %}"><i class="icons icons-sm icons-table"></i> Result information</a></li>
    <li><a href="{% url 'analyzer:all_results_plot' student.slug %}"><i class="icons icons-sm icons-area-chart"></i> Comparative Analysis</a></li>
    <li><a href="{% url 'analyzer:cgpa_by_level' student.slug %}"><i class="icons icons-sm icons-line-chart"></i> {{ student.first_name }}'s CGPA By Level</a></li>
    <li><a href="{% url 'results:all_results' student.slug %}"><i class="icons icons-sm icons-history"></i> Performance History</a></li>
    <li><a href="#"><i class="icons icons-sm icons-payment"></i> Payment History</a></li>
    {% if user.is_superuser %}
    <li><a href="#"><i class="icons icons-sm icons-proceed"></i> Start Clearance Process for {{ student }}</a></li>
    {% endif %}
{% endif %}
{% if request.user.lecturer %}
    <h4><i class="icons icon-md icons-user"></i> Staff Corner</h4>
    <li><a href="{% url 'assignment:create_assignment' %}"><i class="icons icons-sm icons-plus"></i> Add New Asignment</a></li>
    <li><a href="{% url 'assignment:staff_assignments' %}"><i class="icons icons-sm icons-book"></i> All Asignments</a></li>
    <li><a href="{% url 'results:staff_result' %}"><i class="icons icons-sm icons-list"></i> All Results </a></li>
    <li><a href="{% url 'supervision' %}"><i class="icons icons-sm icons-book"></i> Project Supervision</a></li>
    <h4><i class="icons icon-md icons-info"></i> Other Actions</h4>
    <li><a href="{% url 'students:students_list' %}">Perform Appraisal </a></li>
    <li><a href="{% url 'results:add_result' %}"><i class="icons icons-sm icons-plus"></i> Add Exam Results in Singleton </a></li>
{% endif %}
{% if request.user.student %}
    <li><a href="#"><i class="icons icons-sm icons-laptop"></i> Transcript Lite</a></li>
    <li><a href="{% url 'results:personal_results' request.user.student.slug %}"><i class="icons icons-sm icons-table"></i> Result information</a></li>
    <li><a href="{% url 'collaborate:friend-zone' %}"><i class="icons icons-sm icons-group"></i> Add a Friend</a></li>
    <li><a href="{% url 'courses:course-registered' %}"><i class="icons icons-sm icons-table"></i> Registered Courses</a></li>
    <h4><i class="icons icons-sm icons-area-chart"></i> Analysis</h4>
    <li><a href="{% url 'analyzer:all_results_plot' request.user.student.slug %}"><i class="icons icons-sm icons-area-chart"></i> Comparative Analysis</a></li>
    <li><a href="{% url 'analyzer:cgpa_by_level' request.user.student.slug %}"><i class="icons icons-sm icons-line-chart"></i> CGPA Analysis</a></li>
    <li><a href="{% url 'results:all_results' request.user.student.slug %}"><i class="icons icons-sm icons-area-chart"></i> Performance History</a></li>
    <h4><i class="icons icons-sm icons-payment"></i> Payment History</h4>
    <li><a href="#"><i class="icons icons-sm icons-money"></i> Check All Payments</a></li>
    <li data-toggle="popover" title="This feature will be available in version 2.0 where you can pay from your account directly with no bank hustle"><a href="#"><i class="icons icons-sm icons-payment"></i> Make Payment <small style="font-size: 10px;">[<i class="icons-sm icons icons-info"></i> Soon]</small></a></li>
{%endif %}

analyzer/templates/analyzer/test_file.html
{% extends 'staff/dashboard.html' %}
{% load staticfiles %}

{% block extrahead%}
  
{% endblock %}

{% block side_panel %}
    
{% endblock %}

{% block breadcrumbs %}
{% if user.is_staff %}<a href="{% url 'students:students_list' %}">All students &raquo;</a>{% endif %} {{ student }}'s CGPA Analysis
{% endblock %}

{% block menu %}
    {% include "analyzer/attached.html" %}
{% endblock %}

{% block content %}
    <div>
        <h2 style="font-weight: bold; color: #c14; border-bottom: 1.3px solid #1c4;"> {{ student }}'s CGPA Level Progress</h2>
    </div>
    <div class="row">
        <div class="panel panel-danger" style="margin: 10px 20px 35px 35px;">
            <div class="panel-heading">CGPA Analysis</div>
            <div class="panel-body">
                <div id="{{ chartID }}">
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-left: 8px; margin-right: 8px; box-shadow: 1px 2px 4px;">
        <div class="col-md-6">
           <h3>CURRENT FCGPA: <span style="color: #c14; border-bottom: 1px solid #1c4; border-top: 1px solid #1c4;"><strong>{{ fcgpa }}</strong></span></h3>
        </div>
        <div class="col-md-6">
              <h4 style="font-weight: bold; text-align: center; ">{{ degree }}</h4>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    
    <script>
        var chart_id = {{ chartID|safe }}
        var chart = {{ chart|safe }}
        var xAxis = {{ xAxis|safe }}
        var yAxis = {{ yAxis|safe }}
        var series = {{ series|safe }}
        var title = {{ title|safe }}
    </script>
    <script>
      $(function () {
    $(chart_id).highcharts({
        chart: chart,
        title: title,
        xAxis: xAxis,
        yAxis: yAxis,
        series: series
    });
});
        
    </script>
{% endblock %}