core/urls.py
from .views import setup, activate, update_quote, check_user
from django.conf.urls import patterns, url


urlpatterns = patterns('', 
	url(r'^setup/$', setup, name='user-settings'),
	url(r'^activate/$', activate, name='activate'),
	url(r'^update_quote/$', update_quote, name='update_quote'),
	url(r'^check/$', check_user, name='check_user'),

)

result_analytics/urls.py
"""result_analytics URL Configuration
"""

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 
from result_analytics.views import index, home, register_user, register_success
from django.views.static import serve
from .views import home, change_password, activation_sent, activate

urlpatterns = [ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^assignments/', include('assignments.urls', namespace='assignment')),
    url(r'^$', index, name='user_index'),
    url(r'^prompt$', TemplateView.as_view(template_name='_signup_prompt.html'), name='signup-prompt'),
    url(r'^dashboard/$', home, name='dashboard'),
    url(r'^results/', include('results.urls', namespace='results')),
    url(r'^analytics/', include('analyzer.urls', namespace='analyzer')),
    url(r'^staff/', include('staff.urls')),
    url(r'^setup/', include('core.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^notification/', include('notifications.urls', namespace='notifications')),
    url(r'^institution/', include('institutions.urls', namespace='institution')),
    url(r'^collaborate/', include('collaborations.urls', namespace="collaborate")),
    url(r'^forum/', include('forum.urls')),
]
urlpatterns+=patterns('django.contrib.auth.views',
        url(r'^login/$', 'login', {'template_name': 'login.html'}, name='result_login'),
        url(r'^password-reset/$', 'password_reset', {
            'template_name': 'password_reset.html',
            'email_template_name': 'password_reset_email.html',
            'subject_template_name':'password_reset_subject.txt',
            'post_reset_redirect': ('result_reset_done'),
            'html_email_template_name':'password_reset_email.html',
            }, name="result_password_reset"),
        url(r'^password-reset-done/$', 'password_reset_done', {'template_name':'password_reset_done.html',}, name="result_reset_done"),
        url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'password_reset_confirm',{'template_name':'password_reset_confirm.html',}, name="photobox_reset_confirm"),
        url(r'^password-reset-complete/$', 'password_reset_complete',{'template_name':'password_reset_complete.html',}, name="result_reset_complete"), 
        url(r'^logout/$', 'logout', {'next_page': 'result_login'}, name="result_logout"),
)

urlpatterns+=patterns('',
        url(r'^successful/$', register_success, name="result_success"),
        url(r'^signup/$', register_user, name="result_signup"),
        url(r'^start/signup/$', TemplateView.as_view(template_name='signup.html'), name="start-signup"),
        url(r'^change-password/$', change_password, name="change-password"),
        url(r'^howitworks$', TemplateView.as_view(template_name= 'how.html'), name='how-it-works'),
        url(r'^who-we-are/$', TemplateView.as_view(template_name='about.html'), name='about'),
        url(r'^pricing$', TemplateView.as_view(template_name='pricing.html'), name='pricing'),
        url(r'^account_activation_sent/$', activation_sent, name='account_activation_sent'),
        url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

results/urls.py
from django.conf.urls import patterns, url
from .views import (
                add_result, result_list,
                upload_csv, grading_setting, result_by_student, 
                import_data, export_excel, full_detail, 
                overall_result, StaffBasedResultView, edit_result
                )

urlpatterns = patterns('',
    url(r'^add_results/$', add_result, name='add_result'),
    url(r'^edit-result/$', edit_result, name='edit_result'),
    url(r'^grading-scheme$', grading_setting, name='grading-setting'),
    url(r'^upload_csv/$', upload_csv, name='upload_csv'),
    url(r'^lecturer-results/$', StaffBasedResultView.as_view(), name='staff_result'),
    url(r'^import_results/$', import_data, name='result_import'),
    url(r'^students_import/$', import_data, name='student_import'),
    url(r'^$', result_list, name='students_results'),
    url(r'^own_results/(?P<student_slug>[\w-]+)/$', result_by_student, name='personal_results'),
    url(r'^overall_results/(?P<student_slug>[\w-]+)/$', overall_result, name='all_results'),
    url(r'^(?P<student_slug>[\w-]+)/result_details/$', full_detail, name='full_detail'),
    url(r'^excel/$', export_excel, name='export_excel'),
)

students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .forms import *
from .views import (StudentListView, student_profile, request_help,
                    export_excel, create_student, update_photo, student_chart_json,
                    mapper_excel_generator, generate, generate_mapper_json,
                    edit_profile, StudentAnalyticsView, import_student_data, upload_student_csv)
urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^analysis/$', login_required(StudentAnalyticsView.as_view()), name='student_analytics'),
    url(r'^new_student/$', create_student, name='create_student'),
    url(r'^profile/(?P<student_slug>[\w-]+)/$', student_profile , name='student_account'),
    url(r'^excel/$', export_excel, name='export_excel'),
    url(r'^mapper/$', mapper_excel_generator, name='mapper'),
    url(r'^update-profile/$', edit_profile, name='edit-profile'),
    url(r'^mapper/generator/$', generate, name='generate'),
    url(r'^update-photo/$', update_photo, name='update_photo'),
    url(r'^student-json/$', student_chart_json, name='student_chart_json'),
    url(r'^mapper-json/$', generate_mapper_json, name='mapper-json'),
    url(r'^ineed/assistance/(?P<student_id>\d+)/$', request_help , name='help'),
    url(r'^bulk-upload/$', import_student_data , name='student-import'),
    url(r'^upload/$', upload_student_csv , name='student-upload'),

)

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class Category(models.Model):
	name = models.CharField(max_length=50)

	class Meta:
		verbose_name = _(u'Forum Category')
		verbose_name_plural = _(u'Forum Categories')
		ordering = ('name',)

	def __str__(self):
		return self.name

	def last_post(self):
		if self.post_set.count():
			return self.post_set.order_by("created")[0]


class Post(models.Model):
	POST_CHOICES = (
		('Q', 'Question'),
		('I', 'Idea')
	)
	user = models.ForeignKey(User)
	title = models.CharField(max_length=50)
	post_type = models.CharField(max_length=1, choices=POST_CHOICES)
	category = models.ForeignKey(Category)
	question_or_idea = models.TextField(_(u'Your question or Idea to Share'), 
						help_text="Make your post as clear as possible for quick feedback")
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = _(u'Post')
		verbose_name_plural = _(u'Posts')

	def __str__(self):
		return self.title


class Response(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	comment = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-date_created',)

	def __str__(self):
		return "%s - %s" % (self.user.last_name, self.comment[:20])


class Reply(models.Model):
	user = models.ForeignKey(User)
	response = models.ForeignKey(Response)
	comment = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.comment[:20]

class ProfaneWord(models.Model):
    word = models.CharField(max_length=60)

    def __str__(self):
        return self.word

results/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from courses.models import Course
from django.conf import settings
from decimal import Decimal
from django.db.models import Sum
from staff.models import Lecturer
from students.models import Student
from institutions.models import Department, Institution
from functools import reduce

def decimal_add(x, y):
    '''
    This is an operator for a decimal addition. 
    '''
    return Decimal(x) + Decimal(y)

class Grading(models.Model):
    institution = models.ForeignKey(Institution, null=True)
    caption = models.CharField(max_length=15, null=True)
    grade_points = models.DecimalField(max_digits=2, decimal_places=1, null=True)
    start = models.IntegerField(null=True, default=0)
    end = models.PositiveIntegerField(null=True, default=100)

    class Meta:
        verbose_name = _(u'Grading')
        verbose_name_plural = _(u'Gradings')
        ordering = ('caption',)

    def __str__(self):
        return self.caption

class ResultManager(models.Manager):

    def get_staff_results(self, request):
        return self.filter(course__lecturers=request.user.lecturer)


class Result(models.Model):
    student = models.ForeignKey(Student, null=True)
    course = models.ForeignKey(Course, null=True)
    exam_score = models.DecimalField(null=True, default=0.0, decimal_places=2, max_digits=6)
    assignment_score = models.DecimalField(null=True,  default=0.0, decimal_places=2, max_digits=6)
    quiz_score = models.DecimalField(null=True, default=0.0, decimal_places=2, max_digits=6)
    total_score = models.DecimalField(null=True, default=0.0, decimal_places=2, max_digits=6)
    level = models.PositiveIntegerField(choices=settings.LEVEL_CHOICES,null=True, blank=True)
    semester = models.PositiveIntegerField(choices=settings.SEMESTER_CHOICES, null=True)
    department = models.ForeignKey(Department, null=True, blank=True)
    institution = models.ForeignKey(Institution, null=True)
    credit_load = models.DecimalField(default=0.0, decimal_places=2, max_digits=4, blank=True, null=True)
    session = models.CharField(max_length=10, blank=True, null=True)
    course_load = models.DecimalField(default=0.0, decimal_places=2, max_digits=4, blank=True, null=True)
    date_created = models.DateField(auto_now_add=True, null=True)
    date_modified = models.DateTimeField(auto_now=True, null=True)
    modified_by = models.ForeignKey(Lecturer, null=True, blank=True)
    objects = ResultManager()

    class Meta:
        verbose_name = _(u'Student Result')
        verbose_name_plural = _(u' Student Results')
        ordering = ('-date_created',)
        
    def __str__(self):
        return '%s' % (self.total_score)
    
    def save(self, **kwargs):
        self.credit_load = self.get_credit_load
        self.course_load = self.get_course_load
        self.department = self.student.department
        self.total_score = self.get_total_score()
        
        super(Result, self).save(**kwargs)

    @property
    def grade(self):
        score = self.get_total_score()
        grades = Grading.objects.filter(institution=self.student.institution)
        grade = [grade.caption for grade in grades if score in range(grade.start, grade.end+1)]
        
        return grade[0]
    
    def get_total_score(self):
        total = reduce(decimal_add, [self.exam_score,self.assignment_score, self.quiz_score, 0.0])
        return total

    @property
    def grade_points(self):
        grade = self.grade
        grading = Grading.objects.get(institution=self.student.institution, caption=grade)
        return grading.grade_points
    
    @property
    def get_credit_load(self):
        return self.course.unit
    
    @property
    def get_course_load(self):
        course_load = Decimal((self.course.unit*self.grade_points))
        return course_load


class CGPA(models.Model):
    student = models.ForeignKey(Student)
    cgpa = models.DecimalField(verbose_name='student_cgpa', max_digits=3,decimal_places=2)
    semester = models.PositiveIntegerField(choices=settings.SEMESTER_CHOICES, null=True)
    level = models.PositiveIntegerField(null=True)
    session = models.CharField(max_length=15)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s for semester %s %s session' % (self.cgpa, self.semester, self.session)

    class Meta:
        verbose_name = _(u'CGPA')
        verbose_name_plural = _(u'CGPAs')
        ordering = ('-date_created',)
        

results/forms.py
from django import forms
from .models import Result, CGPA, Grading
from .fields import RestrictedFileField

class BatchResultForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        super(BatchResultForm, self).__init__(*args, **kwargs)
        self.fields['semester'].widget.attrs = {'placeholder' : _(u'Full name'), 'class': 'form-control', 'style': 'height: 19px;'}
        self.fields['course'].widget.attrs = {'placeholder' : _(u'Email'), 'class': 'form-control'}
        self.fields['session'].widget.attrs = {'placeholder' : _(u'Subject'), 'class': 'form-control'}
        self.fields['course_load'].widget.attrs = {'placeholder' : _(u'Phone'), 'class': 'form-control'}
        self.fields['level'].widget.attrs = {'placeholder' : _(u'Message'), 'class': 'form-control', 'rows': '10'}
        self.fields['credit_load'].widget.attrs = {'placeholder' : _(u'Message'), 'class': 'form-control', 'rows': '10'}

    class Meta:
        model = Result
        exclude = ('semester', 'course', 'date_created', 'session', 'level', 'course_load', 'credit_load')
        
class ResultForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        super(BatchResultForm, self).__init__(*args, **kwargs)
        self.fields['student'].widget.attrs = {'placeholder' : _(u'Full name'), 'class': 'form-control', 'style': 'height: 19px;'}
        self.fields['course'].widget.attrs = {'placeholder' : _(u'Email'), 'class': 'form-control'}
        self.fields['session'].widget.attrs = {'placeholder' : _(u'Subject'), 'class': 'form-control'}
        self.fields['level'].widget.attrs = {'placeholder' : _(u'Message'), 'class': 'form-control', 'rows': '10'}
       
    class Meta:
        model = Result
        exclude = ('date_created', 'course_load', 'credit_load', 'department')
        

    
class ImportForm(forms.Form):
    # File size limited to 2MB
    file = RestrictedFileField(
        label='Upload File (Max Size 2MB)',
        content_types=[
            'application/binary',
            'application/ms-excel',
            'application/csv',
            'application/octet-stream',
            'application/vnd.ms-excel',
            'text/csv',
            'text/plain',
        ],
        max_upload_size=2097152,
    )


class BatchGradingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BatchGradingForm, self).__init__(*args, **kwargs)
        self.fields['caption'].widget.attrs = {'class': 'form-control input-sm', 'placeholder': 'Grade Letter'}
        self.fields['grade_points'].widget.attrs = {'class': 'form-control input-sm', 'placeholder': 'Grade Point'}
        self.fields['start'].widget.attrs = {'class': 'form-control input-sm'}
        self.fields['end'].widget.attrs = {'class': 'form-control input-sm'}

    class Meta:
        model = Grading
        exclude = ('institution',)


class GradingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GradingForm, self).__init__(*args, **kwargs)
        self.fields['institution'].widget.attrs = {'class': 'form-control input-sm'}

    class Meta:
        model = Grading
        fields = ('institution',)

results/templates/results/_edit_result.html
{% load static thumbnail %}
<div id="{{result.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title"><strong>Result Details</h3>
      </div>
      <form method="post" id="frm_submit" action="{% url 'results:edit_result' %}">{% csrf_token %}
        <div class="modal-body">
          <div class="row" style="margin-left: 0px;">
            <div class="col-md-9" style="padding: 1px;">
              <div class="panel panel-default" style="padding: 0 5px;">
                <p>Reg Number: <span style="float: right; font-weight: 600;">{{ result.student.reg_number}}</span></p>
                <p>Department: <span style="float: right; font-weight: 600;">{{ result.student.department}}</span></p>
                <p>Course Code: <span style="float: right; font-weight: 600;">{{ result.course.course_code}}</span></p>
                <p>Course Title: <span style="float: right; font-weight: 600;">{{ result.course}}</span></p>
                {% if result.submitted.answer %}
                <p>Answer: <span style="float: right; font-weight: 600;">{{ result.submitted.answer}}</span></p>
                {% endif %}
                <p>Date Entered: <span style="float: right; font-weight: 600;">{{ result.date_created}}</span></p>
                <p>Date Last Modified: <span style="float: right; font-weight: 600;">{% if result.modified_by %}{{ result.date_modified}}{% else %} Not modified yet{% endif %}</span></p>
                <p>Modified By: <span style="float: right; font-weight: 600;">{% if result.modified_by %}{{ result.modified_by}}{% else %} Not modified yet{% endif %}</span></p>            
              </div>
            </div>
            <div class="col-md-3">
              <div class="panel panel-default" style="text-align: center; padding-top: 10px;">
                {% if result.student.photo %}
                {% thumbnail result.student.photo "100x100" crop="top" as im %}
                <img src="{{im.url}}" alt="" class="img-circle">
                {% endthumbnail %}
                {% else %}
                <img src="{% static 'images/avatar.png' %}" alt="" height="100" width="100" class="img-circle">
                {% endif %}
                <h5 style="padding: 5px 7px;"><strong>{{ result.student}}</strong></h5>
              </div>
            </div>
          </div>
          <div class="panel panel-default" style="padding: 0 10px;">
            <div class="sub-panel add-padding">
              <h5>All Available Scores</h5>
            </div>
              <div class="form-group">
                <label for="">Quiz Score</label>
                <input type="number" name="quiz_score" class="form-control" value="{{result.quiz_score}}">
              </div>
              <div class="form-group">
                <label for="">Assignment Score</label>
                <input type="number" name="assignment_score" class="form-control" value="{{result.assignment_score}}">
              </div>
              <div class="form-group">
                <label for="">Exam Score</label>
                <input type="number" name="exam_score" class="form-control" value="{{result.exam_score}}">
              </div>
              <input type="hidden" name="result_id" value="{{result.id}}">
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-sm custom-btn">Update Scores</button>
          <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </form>
    </div>

  </div>
</div>

results/templates/results/add_results.html
{% extends 'dashboard.html' %}

{% load staticfiles %}
{% load form_tags %}

{% block content %}
    <h3 class="page-header">Enter Single Results</h3>
<div class="col-md-8 center-block panel panel-default">
    <div class="sub-panel add-padding">
        <h5>New Result</h5>
    </div>
    <form id="from-submit" class="form-horizontal" method="post" >{% csrf_token %}
        <div id="div_id_username" class="form-group required">
            <label for="id_username" class="control-label col-md-4  requiredField"> Reg Number:<span class="asteriskField">*</span> </label>
            <div class="controls col-md-8">
                <input required="true" class="input-md  textinput textInput form-control" id="id_reg_number" maxlength="30" name="reg_number" placeholder="Enter a reg number" style="margin-bottom: 10px" type="text" />
            </div>
        </div>
        <div id="div_id_email" class="form-group required">
            <label for="id_course" class="control-label col-md-4  requiredField"> Course:<span class="asteriskField">*</span> </label>
            <div class="controls col-md-8 ">
                <select required="true" class="input-md textinput form-control" id="id_course" name="course">
                    {% for course in courses %}
                    <option value="{{course.course_code}}">{{course}}</option>
                    {% endfor %}
                </select>
            </div>     
        </div>
        <div id="div_id_password1" class="form-group required">
            <label for="id_level" class="control-label col-md-4  requiredField">Level:<span class="asteriskField">*</span> </label>
            <div class="controls col-md-8 "> 
                <select required="true" id="id_level" name="level" class="select form-control" style="margin-bottom: 10px;">
                    <optgroup>
                        <option value="100">100</option>
                        <option value="200">200</option>
                        <option value="300">300</option>
                        <option value="400">400</option>
                        <option value="500">500</option>
                        <option value="600">600</option>
                    </optgroup>
                </select>
                
            </div>
        </div>
        <div id="div_id_number" class="form-group required">
             <label for="id_score" class="control-label col-md-4  requiredField">Exam Score:<span class="asteriskField">*</span> </label>
             <div class="controls col-md-8 ">
                 <input required="true" class="input-md textInput form-control form-control-success" id="id_score" name="score" placeholder="provide a score" min="0" max="100" style="margin-bottom: 10px;" type="number" />
            </div> 
        </div> 
        <div id="div_id_location" class="form-group required">
            <label for="id_semester" class="control-label col-md-4  requiredField"> Semester:<span class="asteriskField">*</span> </label>
            <div class="controls col-md-8 ">
                <select required="true" id="id_semester" name="semester" class="select form-control" style="margin-bottom: 10px;">
                    <option value="1">First Semester</option>
                    <option value="2">Second Semester</option>
                </select>
            </div> 
        </div>
        <div id="div_id_email" class="form-group required">
            <label for="id_session" class="control-label col-md-4  requiredField"> Session:<span class="asteriskField">*</span> </label>
            <div class="controls col-md-8 ">
                <input required="true" class="input-md textinput form-control" id="id_session" name="session" placeholder="Current Session" maxlength="10" style="margin-bottom: 10px" type="text" />
            </div>     
        </div>
        <div class="form-group">
            <div class="controls col-md-offset-4 col-md-8 ">
                <div id="div_id_terms" class="checkbox required">
                    <label for="id_confirm" class=" requiredField">
                         <input required="true" class="input-ms checkboxinput" id="id_confirm" name="confirm" style="margin-bottom: 10px" type="checkbox" />
                         Confirm that all fields are correctly filled
                    </label>
                </div>      
            </div>
        </div> 
        <div class="form-group"> 
            <div class="aab controls col-md-4 "></div>
            <div class="controls col-md-8 ">
                <input type="submit" name="Signup" value="Save" class="btn custom-btn btn-sm btn-block" id="id_submit" />
            </div>
        </div> 
            
    </form>
            </div>
{% endblock %}

 {% block extrajs %}
 <script>
    var btn_submit = document.getElementById("id_submit");
    var chkbox_confirm = document.getElementById("id_confirm");
    btn_submit.disabled = true;
    console.log(chkbox_confirm.checked);

    chkbox_confirm.addEventListener('click', function() {
        if(chkbox_confirm.checked)
            btn_submit.disabled = false;
        else
            btn_submit.disabled = true;
    });
    $(document).on('submit', '#frm-submit', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/results/add_results/',
            data: {
                student: $('#id_student').val(),
                course: $('#id_course').val(),
                score: $('#id_score').val(),
                level: $('#id_level').val(),
                semester: $('#id_semester').val(),
                session: $('#id_session').val(),
                csrfmiddlewaretoken: {{ csrf_token }}
                },
            success: function(response){
                update_messages(data.messages);
            }
        });
        e.preventDefault();
    });

    function update_messages(messages){
        $("#notification").html("");
        $.each(messages, function (i, m) {
                $("#notification").append("<div class='alert alert-"+m.tags+"''>"+m.message+"</div>");
            });
    }
 </script>
    
{% endblock %}  

results/templates/results/cgpa.html
{% extends 'dashboard.html' %}

{% block title%}
CGPA
{% endblock %}
{% block breadcrumbs %}
<a style="text-decoration: none; color: #c16;" href="#">Student's CGPA</a>&raquo;
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <h1 style='font-family: Sansation Light;'>Current CGPA</h1>
    <div>
        <h4>{{ message }}</h4>
    </div>
    <div>
       {% if cgpa %}
       <h1>{{ cgpa.student }}'s CGPA </h1>
       <table class='table table-striped'>
        <thead>
            <caption>Your Student ID is :{{ cgpa.student.id }}</caption>
        </thead>
        <tbody>
            <tr>
                <th>Full Name:</th>
                <td>{{ cgpa.student }}</td>
            </tr>
            <tr>
                <th>Department:</th>
                <td>{{ cgpa.student.department }}</td>
            </tr>
            <tr>
                <th>Current CGPA:</th>
                <td>{{ cgpa.cgpa|floatformat:'2' }}</td>
            </tr>
        </tbody>
       </table>
       {% endif %}
    </div>
    {{ data }}
</div>
{% endblock %}

results/templates/results/staff_result_list.html
{% extends 'dashboard.html' %}
{% load record_filters %}

{% block extra_css %}
<style>
    input[type=text] {
        height: 26px;
        font-size: 13px;
    }
</style>
{% endblock %}

{% block title %}Results{% endblock %}
{% block breadcrumbs %}
    All results
{% endblock %}
{% block content %}
    <div style="margin-bottom: 30px;">
       <h3 class="page-header head-color">Your Result List</h3>
    </div>
<div class='container-fluid '>
    <table class='table table-condensed table-hover'>
        <thead>
            <tr>
                <th style="width: 3%;">&nbsp;</th>
                <th scope="col" style="width: 13%;">Reg Number</th>
                <th scope="col" style="width: 32%;">Course <span><i class="icons icons-info" data-toggle="popover" title="Click the course or reg number to edit score"></i></span></th>
                <th scope="col" style="width: 7%;">Semester</th>
                <th scope="col" style="width: 4%;">Level</th>
                <th scope="col" style="width: 5%;">Score</th>
                <th scope="col" style="width: 6%;">Grade</th>
                <th scope="col" style="width: 12%;">Date Entered</th>
            </tr>
        </thead>
        <tbody>
        {% if results %}
            {% for result in results %}
            <tr class="">
                <td>{{forloop.counter}}</td>
                <td><a href="#{{result.id}}"  data-toggle="modal">{{ result.student.reg_number }}</a></td>
                <td><a href="#{{result.id}}"  data-toggle="modal">{{ result.course }}</a></td>
                <td>{{ result.semester }}</td>
                <td>{{ result.level }}</td>
                <td>{{ result.total_score }}</td>
                <td style="text-align: left;">{{ result.grade }}</td>
                <td>{{ result.date_created }}</td>
            </tr>
            {% include 'results/_edit_result.html' %}
            {% endfor %}
        {% else %}
            <tr><td colspan="8" style="text-align: center;">No records to display</td></tr>
        {% endif %}
        </tbody>
    </table>
</div>
<div>
    {% render_paginator results %}
</div>
{% endblock %}

{% block side %}
<div class="panel panel-default" style="min-height: 200px; margin-top: 5px;">
    <div class="panel-body">
        <div class="sub-panel">
            <h4><strong>Query Filter</strong></h4>
        </div>
        <form action="">
            <div class="form-group">
                <label for="id_reg">Reg Number:</label>
                <input type="text" name="reg_number" class="form-control" placeholder="Reg number">
            </div>
            <div class="form-group">
                <label for="id_level">By Level:</label>
                <select name="level" class="form-control input-sm" id="id_level">
                <option value="all">Select Level</option>
                <option value="100">100 Level</option>
                <option value="200">200 Level</option>
                <option value="300">300 Level</option>
                <option value="400">400 Level</option>
                <option value="500">500 Level</option>
                <option value="600">600 Level</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_course">By Course:</label>
                <select id="id_course" name="course_id" class="form-control input-sm">
                <option value="all">Select Course</option>
                {% for course in courses %}
                <option value="{{course.id}}">{{course}}</option>
                {% endfor %}
                </select>
                <small class="text-muted">[Showing courses that you lecture only]</small>
            </div>
            <div class="form-group">
                <label for="id_category">By Department:</label>
                <select name="dept_id" id="" class="form-control input-sm">
                <option value="all">Select Department</option>
                {% for department in departments %}
                <option value="{{department.id}}">{{department}}</option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-sm custom-btn" type="search">Filter Queryset</button>
            </div>
        </form>
    </div>
</div>

<div class="panel panel-default">
  <div class="sub-panel add-padding">
    {% if request.user.is_staff %}
     <button class="btn btn-sm custom-btn"><i class="icons icons-sm icons-vcard"></i> Connect with a Staff</button>
     {% endif %}
  </div>
</div>
{% endblock %}